### ISSUE TITLE
Provide passthrough search OCAP

### ISSUE THREAD

**Issue by dougmet** [MangoTheCat/rcloud.solr#41]
Provide another route through to solr for rapid search. This is all based on speed so do as little processing in R as possible:

1. Only search `main_source`
2. Do not parse solr result. Return direct.

@shaneporter can add further requirements.

**Comment by shaneporter** [comment]
Thanks @dougmet - afaik, I need to be able to search on notebook name and user (though not the whole string, as it's an incremental search). 

What comes back from solr? I probably only need the user, notebook name and last modified date. Do you also have access to the number of stars for that notebook? That might be quite a cool thing to use in the search results.

**Comment by shaneporter** [comment]
This is the sort of matching that I'd like. A search string `pac` matches:

<pre>
<b>pac</b>kage.json
<b>p</b>opul<b>a</b>tion.<b>c</b>sv
</pre>

![image](https://user-images.githubusercontent.com/2493614/30647350-1b6a3fe6-9e13-11e7-9251-0c62a49e295e.png)

**Comment by dougmet** [comment]
is pac inside the `population.csv` contents? Just checking what I'm searching against

**Comment by shaneporter** [comment]
It's in the filename. It's matching because it's found a 'p', 'a' and a 'c' in that order. They don't have to be adjacent to one another. (as they are in 'package.json', for example)

**Comment by dougmet** [comment]
oh I see. OK. Will think about how (if it's possible) to do that in lucene format

**Comment by shaneporter** [comment]
In the short term, I'm happy to go for a simpler search match on the name.

**Comment by dougmet** [comment]
ok, in first instance i'll use a wildcard `pac*`. If we're going to need anything fancier it might need changes to the schema, so better we find that out sooner than later!

**Comment by dougmet** [comment]
To reindex all notebooks try this:

```r
users <- rcloud.get.users()

notebooks <- unname(unlist(rcloud.config.all.notebooks.multiple.users(users)))

for (i in notebooks) {
    print(paste0("Indexing ", i))
    result = tryCatch({
    x = rcloud.get.notebook(i)
         rcloud.solr::update_solr(x,rcloud.notebook.star.count(i))
    }, warning = function(w) {
   print(paste0(w," ",i))
    }, error = function(e) {
   print(paste0(e," ",i))
    }, finally = {
    print(paste0("Success ",i))
    })
    Sys.sleep(1)
} 
```

**Comment by shaneporter** [comment]
for reference, I used this:

```R
test <- function() {

users <- rcloud.get.users()

notebooks <- unname(unlist(rcloud.config.all.notebooks.multiple.users(users)))

for (i in notebooks) {
    print(paste0("Indexing ", i))
    result = tryCatch({
    x = rcloud.get.notebook(i)
         rcloud.support:::update.solr(x,rcloud.notebook.star.count(i))
    }, warning = function(w) {
   print(paste0(w," ",i))
    }, error = function(e) {
   print(paste0(e," ",i))
    }, finally = {
    print(paste0("Success ",i))
    })
    Sys.sleep(1)
} 
}
```
